/**
 * Embedding inputs for the catalogue.
 *
 * This module decides *what text represents a place*. It deliberately does not
 * call Gemini: the provider call belongs to the offline pipeline
 * (`src/data/places.ts` -> embed -> normalise -> `place_embeddings`), never to
 * application startup.
 */
import { EMBEDDING_MODEL } from './model'
import { EMBEDDING_DIM } from './vector'
import type { Place } from '@/types'

/** Config the pipeline passes to `ai.models.embedContent`. */
export const EMBEDDING_CONFIG = {
  model: EMBEDDING_MODEL,
  outputDimensionality: EMBEDDING_DIM,
} as const

/**
 * Renders a duration for the embedding text.
 *
 * Deliberately NOT `formatDuration` from the display utils: `content_hash` is
 * derived from this string, so a cosmetic tweak to a UI formatter must never
 * silently invalidate the whole embedding table.
 */
function renderDuration(minutes: number): string {
  const hours = Math.floor(minutes / 60)
  const rest = minutes % 60
  if (!hours) return `${rest} minutes`
  if (!rest) return `${hours} ${hours === 1 ? 'hour' : 'hours'}`
  return `${hours} ${hours === 1 ? 'hour' : 'hours'} ${rest} minutes`
}

/**
 * Builds the text embedded for one place.
 *
 * Every line is drawn from `src/data/places.ts` — nothing here infers or
 * invents an attribute. Fields are included when they carry semantic signal a
 * traveller might search for (what it is, where it is, what it's like, how long
 * it takes, roughly what it costs) and omitted when they are noise for
 * retrieval (rating, review count, coordinates, media keys).
 *
 * The exact formatting is load-bearing: `content_hash` is the SHA-256 of this
 * string, and the pipeline skips any place whose hash is unchanged. Editing the
 * layout below invalidates every stored hash and re-embeds the whole catalogue
 * on the next run — correct, but not free. Change it deliberately.
 */
export function buildPlaceEmbeddingText(place: Place): string {
  const lines = [
    place.name,
    `${place.category} · ${place.city}, ${place.region}`,
    place.summary,
    place.description ?? '',
    place.tags.length ? `Tags: ${place.tags.join(', ')}` : '',
    place.typicalDurationMinutes
      ? `Typical visit: ${renderDuration(place.typicalDurationMinutes)}`
      : '',
    place.priceLevel ? `Price level: ${place.priceLevel} of 4` : '',
  ]
  return lines
    .map((line) => line.trim())
    .filter(Boolean)
    .join('\n')
}

/**
 * SHA-256 hex digest, used for change detection on embedding inputs.
 *
 * Web Crypto rather than `node:crypto` so the same function runs unchanged in
 * Node (the pipeline), Deno (the edge function) and the browser.
 */
export async function hashEmbeddingInput(text: string): Promise<string> {
  const bytes = new TextEncoder().encode(text)
  const digest = await globalThis.crypto.subtle.digest('SHA-256', bytes)
  return Array.from(new Uint8Array(digest))
    .map((byte) => byte.toString(16).padStart(2, '0'))
    .join('')
}

/** Everything the pipeline needs to upsert one `place_embeddings` row. */
export interface PlaceEmbeddingInput {
  /**
   * Stable external key — deliberately the slug, never `place.id`.
   *
   * `public.places.id` is a `uuid` generated by the database, while the local
   * catalogue uses readable ids like `plc-carthage`; the two are unrelated.
   * `places.slug` is `text not null unique` and is already the conflict key
   * `seed.sql` upserts on, so it is the only value that joins this catalogue to
   * a database row. The pipeline resolves it to the real `places.id` just
   * before writing `place_embeddings.place_id`.
   */
  slug: string
  model: string
  dim: number
  /** The text that was embedded — kept for debugging, not stored. */
  text: string
  contentHash: string
}

/** Derives the non-vector half of a `place_embeddings` row from a place. */
export async function buildPlaceEmbeddingInput(place: Place): Promise<PlaceEmbeddingInput> {
  const text = buildPlaceEmbeddingText(place)
  return {
    slug: place.slug,
    model: EMBEDDING_MODEL,
    dim: EMBEDDING_DIM,
    text,
    contentHash: await hashEmbeddingInput(text),
  }
}
